### ISSUE TITLE
the problem of login

### ISSUE THREAD

**Issue by zrone** [networking/init-cms-sandbox#20]
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 6 passed to Networking\InitCmsBundle\Menu\MenuBuilder::__construct() must be an instance of Symfony\Component\Translation\Translator, instance of Symfony\Component\Translation\DataCollectorTranslator given, called in /Users/zrone/AppServer/Lion/app/cache/dev/appDevDebugProjectContainer.php on line 4680 and defined") in NetworkingInitCmsBundle:Navbar:admin_navbar.html.twig at line 33.

**Comment by ychadwick** [comment]
Hi there, I have just made a fresh installation of the CMS and was not able to reproduce your error. Are you overriding the default menu builder service "networking_init_cms.menu.admin_menu_builder". The sixth parameter given to the constructor should be the service with the id "translator", please check that your configuration is the same
